[package]
name = "storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "storage"
path = "src/lib.rs"

[dependencies]
opendal = { version = "0.50.2", features = [ "services-fs" ] }
